#!/bin/bash

# Use manifest-tool to create the manifest, given the experimental
# "docker manifest" command isn't available yet on Docker Hub.

#curl -Lo manifest-tool https://github.com/estesp/manifest-tool/releases/download/v1.0.0/manifest-tool-linux-arm64
#chmod +x manifest-tool
docker manifest annotate jstrader/alpine-int-openvpn:latest jstrader/alpine-int-openvpn:arm32v7 --arch arm --variant v7
docker manifest annotate jstrader/alpine-int-openvpn:latest jstrader/alpine-int-openvpn:arm64v8 --arch arm --variant v8
docker manifest create jstrader/alpine-int-openvpn:latest --amend jstrader/alpine-int-openvpn:amd64 --amend jstrader/alpine-int-openvpn:arm32v7 --amend jstrader/alpine-int-openvpn:arm64v8
docker manifest inspect jstrader/alpine-int-openvpn:latest
#./manifest-tool push from-spec multi-arch-manifest.yaml